namespace NeuroTune;

public enum ProbeSource { Registry, Wmi, Command, CpuId, OptionalTelemetry }
public enum RegistryProbeHive { CurrentUser, LocalMachine }
public enum RegistryValueType { DWord, String }

public sealed record ProbeDefinition(
    string StableEvidenceId,
    string Category,
    RegistryProbeHive Hive,
    string Path,
    string ValueName,
    RegistryValueType ExpectedType,
    string Interpretation)
{
    public ProbeSource Source => ProbeSource.Registry;
    public EvidencePrivacy Privacy => EvidencePrivacy.SystemConfiguration;
    public string SupportedSystems => "Windows 11";
    public string AbsenceSemantics => "Not configured; Windows or the owning application controls the default.";
    public string SourceNote => "Read-only local Registry query.";
    public string ProfileKey => StableEvidenceId["registry:".Length..];
}

public static class ProbeCatalog
{
    public static IReadOnlyList<ProbeDefinition> Registry { get; } =
    [
        new(@"registry:HKCU\Software\Microsoft\GameBar\AutoGameModeEnabled", "Gaming", RegistryProbeHive.CurrentUser, @"Software\Microsoft\GameBar", @"AutoGameModeEnabled", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\GameBar\AllowAutoGameMode", "Gaming", RegistryProbeHive.CurrentUser, @"Software\Microsoft\GameBar", @"AllowAutoGameMode", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\System\GameConfigStore\GameDVR_Enabled", "Gaming", RegistryProbeHive.CurrentUser, @"System\GameConfigStore", @"GameDVR_Enabled", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR\AppCaptureEnabled", "Gaming", RegistryProbeHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\GameDVR", @"AppCaptureEnabled", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Policies\Microsoft\Windows\GameDVR\AllowGameDVR", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\Windows\GameDVR", @"AllowGameDVR", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\HwSchMode", "Graphics", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", @"HwSchMode", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects\VisualFXSetting", "Shell", RegistryProbeHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects", @"VisualFXSetting", RegistryValueType.DWord, "Observe the effective shell configuration without changing it."),
        new(@"registry:HKCU\Control Panel\Mouse\MouseSpeed", "Input", RegistryProbeHive.CurrentUser, @"Control Panel\Mouse", @"MouseSpeed", RegistryValueType.String, "Observe the effective input configuration without changing it."),
        new(@"registry:HKCU\Control Panel\Mouse\MouseThreshold1", "Input", RegistryProbeHive.CurrentUser, @"Control Panel\Mouse", @"MouseThreshold1", RegistryValueType.String, "Observe the effective input configuration without changing it."),
        new(@"registry:HKCU\Control Panel\Mouse\MouseThreshold2", "Input", RegistryProbeHive.CurrentUser, @"Control Panel\Mouse", @"MouseThreshold2", RegistryValueType.String, "Observe the effective input configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling\PowerThrottlingOff", "Power", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Power\PowerThrottling", @"PowerThrottlingOff", RegistryValueType.DWord, "Observe the effective power configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\NetworkThrottlingIndex", "Scheduler", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", @"NetworkThrottlingIndex", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\SystemResponsiveness", "Scheduler", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", @"SystemResponsiveness", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\LargeSystemCache", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", @"LargeSystemCache", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\DisablePagingExecutive", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", @"DisablePagingExecutive", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows\Dwm\OverlayTestMode", "Graphics", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\Dwm", @"OverlayTestMode", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl\Win32PrioritySeparation", "Scheduler", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\PriorityControl", @"Win32PrioritySeparation", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games\GPU Priority", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", @"GPU Priority", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games\Priority", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", @"Priority", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games\Scheduling Category", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", @"Scheduling Category", RegistryValueType.String, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games\SFIO Priority", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", @"SFIO Priority", RegistryValueType.String, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\TcpTimedWaitDelay", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"TcpTimedWaitDelay", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\MaxUserPort", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"MaxUserPort", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\DefaultTTL", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"DefaultTTL", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrDelay", "Graphics", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", @"TdrDelay", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrDdiDelay", "Graphics", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", @"TdrDdiDelay", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity\Enabled", "Security", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity", @"Enabled", RegistryValueType.DWord, "Observe the effective security configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power\HiberbootEnabled", "Power", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Power", @"HiberbootEnabled", RegistryValueType.DWord, "Observe the effective power configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\FileSystem\NtfsDisableLastAccessUpdate", "Storage", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\FileSystem", @"NtfsDisableLastAccessUpdate", RegistryValueType.DWord, "Observe the effective storage configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\DirectX\UserGpuPreferences\DirectXUserGlobalSettings", "Windows", RegistryProbeHive.CurrentUser, @"Software\Microsoft\DirectX\UserGpuPreferences", @"DirectXUserGlobalSettings", RegistryValueType.String, "Observe the effective windows configuration without changing it."),
        new(@"registry:HKCU\System\GameConfigStore\GameDVR_FSEBehaviorMode", "Gaming", RegistryProbeHive.CurrentUser, @"System\GameConfigStore", @"GameDVR_FSEBehaviorMode", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\System\GameConfigStore\GameDVR_HonorUserFSEBehaviorMode", "Gaming", RegistryProbeHive.CurrentUser, @"System\GameConfigStore", @"GameDVR_HonorUserFSEBehaviorMode", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\System\GameConfigStore\GameDVR_DXGIHonorFSEWindowsCompatible", "Gaming", RegistryProbeHive.CurrentUser, @"System\GameConfigStore", @"GameDVR_DXGIHonorFSEWindowsCompatible", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\System\GameConfigStore\GameDVR_EFSEFeatureFlags", "Gaming", RegistryProbeHive.CurrentUser, @"System\GameConfigStore", @"GameDVR_EFSEFeatureFlags", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\GameBar\UseNexusForGameBarEnabled", "Gaming", RegistryProbeHive.CurrentUser, @"Software\Microsoft\GameBar", @"UseNexusForGameBarEnabled", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\GameBar\ShowStartupPanel", "Gaming", RegistryProbeHive.CurrentUser, @"Software\Microsoft\GameBar", @"ShowStartupPanel", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR\HistoricalCaptureEnabled", "Gaming", RegistryProbeHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\GameDVR", @"HistoricalCaptureEnabled", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrLevel", "Graphics", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", @"TdrLevel", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrDebugMode", "Graphics", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", @"TdrDebugMode", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\DisableOverlays", "Graphics", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", @"DisableOverlays", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows\Dwm\EnableMPO", "Graphics", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows\Dwm", @"EnableMPO", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\AlwaysOn", "Scheduler", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", @"AlwaysOn", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\NoLazyMode", "Scheduler", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", @"NoLazyMode", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\LazyModeTimeout", "Scheduler", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile", @"LazyModeTimeout", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games\Clock Rate", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", @"Clock Rate", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games\Background Only", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", @"Background Only", RegistryValueType.String, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games\Affinity", "Gaming", RegistryProbeHive.LocalMachine, @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", @"Affinity", RegistryValueType.DWord, "Observe the effective gaming configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl\IRQ8Priority", "Scheduler", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\PriorityControl", @"IRQ8Priority", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl\IRQ16Priority", "Scheduler", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\PriorityControl", @"IRQ16Priority", RegistryValueType.DWord, "Observe the effective scheduler configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\ClearPageFileAtShutdown", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", @"ClearPageFileAtShutdown", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\SecondLevelDataCache", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", @"SecondLevelDataCache", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\IoPageLockLimit", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", @"IoPageLockLimit", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\FeatureSettingsOverride", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", @"FeatureSettingsOverride", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\FeatureSettingsOverrideMask", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", @"FeatureSettingsOverrideMask", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters\EnablePrefetcher", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", @"EnablePrefetcher", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters\EnableSuperfetch", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters", @"EnableSuperfetch", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\FileSystem\NtfsMemoryUsage", "Memory", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\FileSystem", @"NtfsMemoryUsage", RegistryValueType.DWord, "Observe the effective memory configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\FileSystem\NtfsDisable8dot3NameCreation", "Storage", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\FileSystem", @"NtfsDisable8dot3NameCreation", RegistryValueType.DWord, "Observe the effective storage configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Tcp1323Opts", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"Tcp1323Opts", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\EnablePMTUDiscovery", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"EnablePMTUDiscovery", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\DisableTaskOffload", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"DisableTaskOffload", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\EnableTCPChimney", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"EnableTCPChimney", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\EnableRSS", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"EnableRSS", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\EnableDCA", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"EnableDCA", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\SackOpts", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"SackOpts", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\GlobalMaxTcpWindowSize", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"GlobalMaxTcpWindowSize", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\TcpWindowSize", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"TcpWindowSize", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\KeepAliveTime", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\Tcpip\Parameters", @"KeepAliveTime", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\AFD\Parameters\FastSendDatagramThreshold", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\AFD\Parameters", @"FastSendDatagramThreshold", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\AFD\Parameters\DefaultReceiveWindow", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\AFD\Parameters", @"DefaultReceiveWindow", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\AFD\Parameters\DefaultSendWindow", "Network", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\AFD\Parameters", @"DefaultSendWindow", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched\NonBestEffortLimit", "Network", RegistryProbeHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\Windows\Psched", @"NonBestEffortLimit", RegistryValueType.DWord, "Observe the effective network configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard\EnableVirtualizationBasedSecurity", "Security", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\DeviceGuard", @"EnableVirtualizationBasedSecurity", RegistryValueType.DWord, "Observe the effective security configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Control\Lsa\LsaCfgFlags", "Security", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\Lsa", @"LsaCfgFlags", RegistryValueType.DWord, "Observe the effective security configuration without changing it."),
        new(@"registry:HKCU\Control Panel\Keyboard\KeyboardDelay", "Input", RegistryProbeHive.CurrentUser, @"Control Panel\Keyboard", @"KeyboardDelay", RegistryValueType.String, "Observe the effective input configuration without changing it."),
        new(@"registry:HKCU\Control Panel\Keyboard\KeyboardSpeed", "Input", RegistryProbeHive.CurrentUser, @"Control Panel\Keyboard", @"KeyboardSpeed", RegistryValueType.String, "Observe the effective input configuration without changing it."),
        new(@"registry:HKCU\Control Panel\Mouse\MouseSensitivity", "Input", RegistryProbeHive.CurrentUser, @"Control Panel\Mouse", @"MouseSensitivity", RegistryValueType.String, "Observe the effective input configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\mouclass\Parameters\MouseDataQueueSize", "Input", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\mouclass\Parameters", @"MouseDataQueueSize", RegistryValueType.DWord, "Observe the effective input configuration without changing it."),
        new(@"registry:HKLM\SYSTEM\CurrentControlSet\Services\kbdclass\Parameters\KeyboardDataQueueSize", "Input", RegistryProbeHive.LocalMachine, @"SYSTEM\CurrentControlSet\Services\kbdclass\Parameters", @"KeyboardDataQueueSize", RegistryValueType.DWord, "Observe the effective input configuration without changing it."),
        new(@"registry:HKCU\Control Panel\Desktop\MenuShowDelay", "Windows", RegistryProbeHive.CurrentUser, @"Control Panel\Desktop", @"MenuShowDelay", RegistryValueType.String, "Observe the effective windows configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarAnimations", "Shell", RegistryProbeHive.CurrentUser, @"Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", @"TaskbarAnimations", RegistryValueType.DWord, "Observe the effective shell configuration without changing it."),
        new(@"registry:HKCU\Software\Microsoft\Windows\DWM\EnableAeroPeek", "Graphics", RegistryProbeHive.CurrentUser, @"Software\Microsoft\Windows\DWM", @"EnableAeroPeek", RegistryValueType.DWord, "Observe the effective graphics configuration without changing it."),
        new(@"registry:HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU\NoAutoRebootWithLoggedOnUsers", "Update", RegistryProbeHive.LocalMachine, @"SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU", @"NoAutoRebootWithLoggedOnUsers", RegistryValueType.DWord, "Observe the effective update configuration without changing it."),
    ];
}
